### ISSUE TITLE
Add SourceMap in Dev Environment

### ISSUE THREAD

**Issue by samuelheer** [oveleon/contao-theme-compiler-bundle#2]
https://github.com/oveleon/contao-theme-compiler-bundle/blob/be9eb4373ce0925aca9fd88318bb05d946fcb480/contao/classes/FileCompiler.php#L239

It would be very handy if you would add source map in debug Mode:

My working suggestions would be:
$objCompiler->setSourceMap(Config::get('debugMode') ? Compiler::SOURCE_MAP_INLINE : Compiler::SOURCE_MAP_NONE);

Thanks in advance.

**Comment by zoglo** [comment]
@samuelheer I did look at this issue a while ago and it should actually be implemented in a better way and not inline source maps.

**Comment by zoglo** [comment]
Closes as stale - This shouldn't be happening in debug mode but rather be a config option.
Feel free to reopen this issue or create a PR.
